# Base configs
baseurl: "http://photos.surprisingly.works/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by FuzzPawsOokami"
subtitle: "My world, seen through your eyes. "
author: ""
header:
 title: ""
 subtitle: "" 
footer:
 name: "-"
 bio: "♡ FuzzPawsOokami! ♡#67199 @ Discord, FuzzPawsOokami @ Twitter, fuzzydazzleookami @ Instagram"
 github: ""
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: "https://twitter.com/FuzzPawsOokami"
  instagram: "https://www.instagram.com/fuzzydazzleookami/"
  dribbble: ""
  linkedin: ""
  github: "https://www.github.com/angelfluffyookami/"
