# Base configs
baseurl: "http://photography.angelfluffyookami.ga/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by AngelFluffyOokami"
subtitle: "My world, seen through your eyes. "
author: "By Ram Patra"
header:
 title: "Photo collection"
 subtitle: "by AngelFluffyOokami" 
footer:
 name: "Heya there! My name is Angel."
 bio: "I am a 16 year old hobby photographer from Mexico, taking pictures of stuff is my passion, I also have many other hobbies, mainly audio, gaming and building stuff with technology."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: "https://twitter.com/OokamiLink"
  instagram: "https://www.instagram.com/angelfluffyookami/"
  dribbble: ""
  linkedin: ""
  github: "https://www.github.com/angelfluffyookami/"
