# Base configs
baseurl: "http://photos.angelfluffyookami.ga/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by AngelFluffyOokami"
subtitle: "My world, seen through your eyes. "
author: "By Ram Patra"
header:
 title: ""
 subtitle: "" 
footer:
 name: "-"
 bio: "FuzzyDazzleOokami!#6719 @ Discord, DazzleOokami @ Twitter, fuzzydazzleookami @ Instagram"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: "https://twitter.com/DazzleOokami"
  instagram: "https://www.instagram.com/fuzzydazzleookami/"
  dribbble: ""
  linkedin: ""
  github: "https://www.github.com/angelfluffyookami/"
