# Base configs
baseurl: "https://angelfluffyookami.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by FuzzPawsOokami"
subtitle: ""
author: ""
header:
 title: ""
 subtitle: "" 
footer:
 name: "-"
 bio: "f45a @ Discord, AutumnOokami @ Twitter"
 github: "AngelFluffyOokami"
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: "https://twitter.com/FuzzPawsOokami"
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: "https://www.github.com/angelfluffyookami/"
